### ISSUE TITLE
Swagger?

### ISSUE THREAD

**Issue by dockstreet** [fortunejs/fortune-micro-api#8]
I'm curious if it's possible to have fortune-micro-api work with Swagger.

I saw these 
https://github.com/swagger-api/swagger-node/tree/master/project-skeletons

But not sure if it would apply?

Thanks in advance!

**Comment by 0x8890** [comment]
I'm sure that it is possible, but I don't see the point.

The reasoning is that Swagger is unnecessary to use in a hypermedia context, and it would even be wrong, i.e. out-of-band information. It's not needed to enumerate all endpoints, because it's already done by the server. It's not needed to put docs about fields in Swagger, since the server gives enough info so that a definition can be dereferenced by the client.

**Comment by dockstreet** [comment]
Got it, we are looking at the various JSON APIs available and one requirement we have is for it to have it provides Swagger documentation, due to widespread adoption.

Our users/consumers come from a WSDL background and are looking for something standardized that can be used with proxy generators etc, so Swagger was picked. 

Hydra (another JSON-LD based API ) will generate Swagger-like docs
http://www.markus-lanthaler.com/hydra/console/?url=http://www.markus-lanthaler.com/hydra/api-demo/
(need to hit the "Load" button to see the api)

Still it isn't in swagger format so I started to look at this implementation to see if it could be plugged in. 

What I really like about fortune-micro-api and what has been built is that it's concise, so it may seem redundant given that it it can be dereferenced without it.

**Comment by 0x8890** [comment]
Hmm, probably the best approach would be to introspect the record type definitions and build up a Swagger doc based on that.

The endpoints are pretty much always the same: *HTTP verb* `/{type}/{id}/{field}` and you can put whatever annotations you want in the fields.

**Comment by dockstreet** [comment]
Thanks! Will give it a try
